Ta 06
Malagor/travel-app pull request #33
Opened 2021-03-02 14:23 UTC by Andrei107Q

Closes: #6 

Виджет часов
![image](https://user-images.githubusercontent.com/58862645/109661795-6889fe80-7b7b-11eb-909c-9e60c64ae67c.png)

Добавлен вывод времени и даты, разделен на два раздела для локального времени и времени выбранной страны.
Переписан на функциональный компонент.
При получении данных нужно будет подправить вывод даты.

2021-03-02 14:26 UTC, Andrei107Q commented on src/components/Clock/Clock.tsx
возможно это лучше перенести в отдельный файл Utils и написать две функции одна для стрелок часов вторая для секунд и минут. насколько это целесообразно?

2021-03-02 14:27 UTC, Andrei107Q commented on src/components/Clock/Clock.tsx
> +    setTimeout(changeHour, 1000 * 60 * 12);
не уверен как  целесообразно ли тут использовать 3 сет таймаута. если есть решение по лучше буду рад.

2021-03-02 14:29 UTC, Andrei107Q commented on src/components/Clock/Clock.tsx
> +    setTimeout(changeHour, 1000 * 60 * 12);
можно попробовать написать каждую секунду добавлять к минутам 1/60 а к часам 1/360, возможно будут проблемы при округлении.

2021-03-02 14:30 UTC, Andrei107Q commented on src/components/Clock/ClockWidget.tsx
> +  const otherCity = "otherCity" ;
после получения АPI будут города. пока заглушки

2021-03-02 14:31 UTC, Andrei107Q commented on src/components/Clock/Time.tsx
> +  const date = new Date();
этот параметр думаю передавать пропсами. ну ояпть же после получения Api будет понятно что приходит и как с этим можно работать

2021-03-03 08:18 UTC, Malagor requested changes
Компонент Clock перепиши на первоначальный вариант вычислений, но только используя функциональный подход и хук useEffect. В компонент тебе нужно будет передавать таймзону и просто отнимать\прибавлять нужное количество часов к часам.

Электронные час сделай отдельным компонентом. Так же они должны быть самостоятельные, максимум что им тоже нужно передавать таймзону

Компонент вывода даты сделай отдельным и так же независимым. Вывод даты сделай зависимым от локали. Локаль можешь получать пропсами. Локаль влияет на формат вывода информации. Так же туда нужно передавать таймзону, потому что может оказаться, что в Париже 8 часов вечера, а в Екатеринбурке 4 часа следующего дня. Это нужно учесть.

Так же сформируй вывод связки виджеты часов + вижет даты, что бы обыграть вышеуказанную ситуацию. То есть для каждых часиков (стрелки + "электронные") своя дата.

И учти остальные коменты по тексту.

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/ClockWidget.tsx
> +export const ClockWidget = (props: TClockWidgetProps) => {
Эту штуку лучше писать так

`export const ClockWidget: FC<TClockWidgetProps> = ({localCity, otherCity}) => {...}`

Такая запись позволит сразу деструкторизировать параметры пропсов

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/ClockWidget.tsx
> +  const otherCity = "otherCity" ;
Если это должно прийти в пропсах, значит получи это из пропсов и передай что-нибудь в пропсы от родителя.

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/ClockWidget.tsx
> +  };
Эти опции перенеси в компоненты, которые их используют. Зачем передавать их от родителя, они же никогда не будут меняться?

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/ClockWidget.tsx
> +          <Clock theme={props.theme} date={date}/>
Зачем передавать data  в Clock когда ты её всегда получаешь как new Date()? Получай её в компоненте, если она нужна. То, что тебе нужно, это передать таймзону, что бы учесть это в вычислениях, но саму дату зачем передавать?

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/ClockWidget.tsx
> +          </div>
Не передавать опции в компонент. Объявить их там.

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/ClockWidget.tsx
> +          <Clock theme={props.theme} date={date}/>
Придумай, как тебе получать таймзону по городу, или, может быть лучше получать её пропсами от родителя?

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/Time.tsx
> +};
Объявить в компоненте. не передавать пропсами.

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/Time.tsx
> +  const date = new Date();
Перенести в компонент

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/Time.tsx
> +  }, [data]);
Вернуть из функции функцию, что бы очищать таймер.

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/Time.tsx
> +
Для отображения даты сделай отдельный компонет. Для отображения "электронных часов" свой компонент.

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/Clock.tsx
> +    setTimeout(changeHour, 1000 * 60 * 12);
Чем тебе не понравилось изначальное решение, где был всего лишь один таймер и где из даты просто берешь часы минуты и секунды, без вот всех этих вычислений??

Так же не понятна логика использования таймаутов.... А почему не интервалы? В общем, эту часть верни на ту  что была, такое решение слишком не подойдет.
Получай каждую секунду новую дату, получай их нее с помощью функций date.getHours(), date.getMinutes(), date.getSeconds() нужные циферки и все. И не забудь все это оберунуть в useEffect что бы колбеком очищать интервал, а не накапливать кучу таймеров сжирая память.

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/Clock.tsx
> +    setTimeout(changeHour, 1000 * 60 * 12);
В принципе не понятно, зачем было править этот компонент? Максимум, что тут нужно было сделать, это учесть таймзону и просто отнимать или прибавлять это от\к количеству часов,  и все...

2021-03-03 08:18 UTC, Malagor commented on src/components/Clock/Clock.tsx
> +    setTimeout(changeHour, 1000 * 60 * 12);
Если хотелось переписать на функциональный, тогда нужно было просто правильно восgользоваться useEffect(), который заменил бы DidMount DidUnmount

2021-03-07 14:04 UTC, closed without merging