Ta 06 remake
Malagor/travel-app pull request #37
Opened 2021-03-07 14:03 UTC by Andrei107Q

Closes: #6

Виджет часов
![image](https://user-images.githubusercontent.com/58862645/110242196-0445b100-7f66-11eb-8c9c-b6b34180d898.png)

подключена новая библиотека moment-timezone для работы с другими часовыми поясами 
виджет отображает локальное и дополнительное время

2021-03-07 16:19 UTC, femiarkh approved these changes

2021-03-07 16:19 UTC, femiarkh commented on src/components/ClockWidget/ClockWidget.tsx
> +import { Clock } from './components/Clock/Clock';
Можно использовать `index.ts` и реэкспорт во избежание подобных путей.

2021-03-07 16:19 UTC, femiarkh commented on src/components/ClockWidget/ClockWidget.tsx
> +  const [timeLocal, setLocalTime] = useState(dateLocal.toLocaleString(i18n.language, optionsTime))
Не логичнее ли было `timeLocal, setTimeLocal`?

2021-03-07 16:19 UTC, femiarkh commented on src/components/ClockWidget/ClockWidget.tsx
> +    setDayOtherCity(dateNowOtherCity.format('ll'))
По всей видимости, этот формат не предусматривает дня недели? Получается, в локальных часах день недели указывается, а в заграничных - нет. Так и задумано?

2021-03-08 16:28 UTC, Malagor requested changes
Сперва посмотри все комменты. Там есть решение вопроса локализации которое потребует существенных переделок.

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +    setDayOtherCity(dateNowOtherCity.format('ll'))
Посмотри такой вариант
![image](https://user-images.githubusercontent.com/20399054/110335103-90260e80-8034-11eb-9eb6-257d6afde45e.png)

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +    setMinLocal(dateNowLocal.getMinutes())
tick  поместить в useCallback

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  }, [])
Тут должна быть зависимость от tick

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  const [timeLocal, setLocalTime] = useState(dateLocal.toLocaleString(i18n.language, optionsTime))
Тэкс, у нас есть одна мааленькая хрень, которую мы должны решить, а именно локализацию.
Я боясь, что ты будешь делать это слишком долго, поскольку там немного ниразу не очевидно, поэтому я сделал это сам. 

### Вот что тебе нужно сделать:
1. Установить еще один пакет `moment `в котором есть локализация. 
> `yarn add moment`

2. Далее в этом файле сделать несколько импортов ПЕРЕД вызовом `moment-timezone`

```
import 'moment/locale/en-gb';
import 'moment/locale/be';
import 'moment/locale/ru';
```
Выглядеть все должно вот так 
![image](https://user-images.githubusercontent.com/20399054/110347683-e9486f00-8041-11eb-9eb1-7bcddae16f13.png)

3. В вызовах `moment` нужно добавить локализацию ![image](https://user-images.githubusercontent.com/20399054/110347965-34fb1880-8042-11eb-9527-4282ddf59408.png)

### Теперь еще один момент.
Если использовать `new Date`, то там нет беларусского языка. То есть нужно либо делать костыль, либо просто использовать библиотеку `moment` для получения обоих дат и локальной и дистанционной.
То есть заменить получение локального времени на 
![image](https://user-images.githubusercontent.com/20399054/110348415-adfa7000-8042-11eb-8123-8328d295c9f8.png)

### Как сделать красиво
Напиши несколько функций, которые будут форматировать время и дату в нужном тебе формате для передачи в компоненты-отрисовщики. То есть в стейте храни только 2 переменные-времени: локальное время и дистанционное время. А при передаче этого времени в компоненты-отрисовщики вызывай функции форматтеры. То есть вызов должен бвыгляеть как то так 
`<Clock time={formateTime()} theme={theme} />`

Этих функций форматеров тебе нужно 3 штуки, для каждого компонента. И пусть они возвращают, например, объект вида `{hour, min, sec}`, который ты будешь распаршивать внутри компонента-отрисовщика.

Вынеси эти функции за пределы компонента, что бы они не перерисовывались каждый раз.

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +};
Эти шутки удалятся в связи с новым алгоритмом работы с датой

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +    const dateNowLocal = new Date()
Оберни в useCallback и он будет зависеть от языка по идее.

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +    setDayOtherCity(dateNowOtherCity.format('ll'))
![image](https://user-images.githubusercontent.com/20399054/110349491-d0d95400-8043-11eb-85e7-80d02881e478.png)

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  const [timeLocal, setLocalTime] = useState(dateLocal.toLocaleString(i18n.language, optionsTime))
Поддерживаю предыдущего оратора. Сделай имена более понятные. Но посмотри сперва далее комментарии, там будут существенные изменения

2021-03-08 16:28 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +import { Clock } from './components/Clock/Clock';
Внутри подпапки components сделай файл index.ts откуда реэкспортируй все внутренние компоненты.
То есть будет файл в котором будут экспорты из всех внутренних компонентов.

2021-03-10 12:14 UTC, Malagor requested changes
Почти отлично. Поправь коменты и пингуй меня

2021-03-10 12:14 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +
Переименуй переменные, типа localTimezone и countryTimezone.
Для получения локального времени в moment есть метод `moment().locale(i18n.language).local()`. Он получает локальное время в той локали (переводе) что нам нужно.

Язык бери из переменной перевода I18n.language или из редакса по пути State.userInfo.lang. В типах можно глянуть путь до языка. 
Для получения языка можно использовать хук const lang = useSelect((state: State) => state.userInfo.lang). Ну, или из переменной перевода.

2021-03-10 12:14 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  const [otherDate, setOtherDate] = useState(dateOtherCity)
тут тоже используй `countryDate`, `counrtyTime`... Будет у нас локальная и время или дата страны

2021-03-10 12:14 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +    const dateOtherCityNow = moment().locale(languageNewYork).tz(timezoneNewYork)
Чем это отличается от 36-37 строки?
И локаль должна быть одинаковая для обоих случаев. Мы выдаем данные на нашем языке, а не на языке страны

2021-03-10 12:14 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +import { DateString } from './components/Date';
С под-папке components сделай Index откуда реэкспортируй все компоненты. Что бы они тут все подключались из папки `./components`

2021-03-10 12:14 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +import { DateString } from './components/Date';
Вот пример. Его пока нет у тебя чтобы посмотреть в реальности 
![image](https://user-images.githubusercontent.com/20399054/110626703-1caa0b80-81b2-11eb-982f-4839ff013492.png)

2021-03-10 12:14 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +const getTimeForForDate = (date: moment.Moment) => date.format('dddd, ll')
Поправь название функции. ForFor.
Можно на какое-нибудь getDate

2021-03-11 08:30 UTC, Malagor reviewed
Ок, мержи. Потом чутка еще подкорректируем, когда будут реальные данные.

2021-03-11 14:41 UTC, merged