fix: fixed style clock widget and connectined in app
Malagor/travel-app pull request #48
Opened 2021-03-11 18:05 UTC by Andrei107Q

1. Поставил заглушку для виджета
![image](https://user-images.githubusercontent.com/58862645/110833388-6cb9c880-82ad-11eb-9557-f007d576a1e2.png)

2. Перенес название дня недели на отдельную строчку, т.к. не влезалет в одну 
было
![image](https://user-images.githubusercontent.com/58862645/110833132-2cf2e100-82ad-11eb-923f-65f169910276.png)
стало
![image](https://user-images.githubusercontent.com/58862645/110833189-3e3bed80-82ad-11eb-9c2a-d46040f34e05.png)

2021-03-12 06:11 UTC, femiarkh approved these changes

2021-03-12 06:11 UTC, femiarkh commented on src/components/ClockWidget/ClockWidget.tsx
> +  const season = date.format('ll')
Не самое удачное название переменной. Season - это время года. А у нас просто дата: число, месяц, год. Можно было day назвать как-нибудь типа dayOfWeek, а season - monthDayYear, было бы чутка понятней.

2021-03-12 06:11 UTC, femiarkh commented on src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
> +const data = {
Вот и назвал был clockWidgetData - комментарий бы писать не пришлось.

2021-03-12 08:36 UTC, Malagor requested changes
Еще важно.
Функцию tick обязательно нужно взять в useCallback. Я вроде писал об этом ранее, но упустил проверить повторно. И поправь остальные коменты

2021-03-12 08:36 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  const season = date.format('ll')
Согласен с предыдущим оратором. Называй переменные осмысленно. Что такое season? Время года?

2021-03-12 08:36 UTC, Malagor commented on src/components/ClockWidget/components/Date/DateString.tsx
> +      { date.season }
Опять такие, что за сезон? Это название нужно попрапвить

2021-03-12 08:36 UTC, Malagor commented on src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
> +const data = {
Согласен

2021-03-12 16:11 UTC, Andrei107Q commented on src/components/ClockWidget/ClockWidget.tsx
> +  const season = date.format('ll')
![image](https://user-images.githubusercontent.com/58862645/110966805-ba463c00-8366-11eb-8432-3ef3feb127ab.png)
у сезона есть еще значения как день. но думаю, да так будет лучше  dayOfWeek // monthDayYear

2021-03-13 10:42 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  const season = date.format('ll')
Как видно из твоего скрина, самый популярный перевод, это "сезон". Наша же задача, когда мы выбираем название переменной, это обозвать её так, что бы не пришлось гадать или лезть в словарь, что это за переменная и зачем она нужна.
В ствоем случае `const season = date.format('ll')` вообще не понятно, что это за формат такой "ll", может это как раз такие "весна, зима, осень..." обозначает. Ведь четко же написано, что это "сезон".

2021-03-13 13:05 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  const monthDayYear = date.format('ll');
Да, так лучше. Можно было обозвать что-то вроде fullDate, но так сойдет. Правда, когда через пару дней тебе придется править виджет, что бы привязать его к базе данных, т ы сам задашься вопросом, а что это за "месяц дня года"?

2021-03-13 13:05 UTC, Malagor commented on src/components/ClockWidget/ClockWidget.tsx
> +  }, [data, i18n]);
Тут зависимость не просто от i18n, а именно от смены языка, то есть от `i18n.language`. Потому что сама библиотека не меняется, меняется определенный параметр.

2021-03-13 13:05 UTC, Malagor commented on src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
> +        <ClockWidget data={clockWidgetData} theme={theme} />
Да, такое решение хорошее. Передавать нужные параметры из вне, а не определять их внутри.

2021-03-13 13:27 UTC, Malagor reviewed
Ок

2021-03-13 13:39 UTC, merged